name: Backup Repository

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"   

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Create backup archive
        run: |
          mkdir -p backup
          tar -czf backup/time-tracker-$(date +%F-%H%M).tar.gz .
      
      - name: Cleanup Workspace
        if: always()
        run: |
          echo "Backup workflow finished."