name: Install Nginx

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-nginx:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Install Nginx
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nginx

      
      - name: Verify Nginx
        run: |
          nginx -v
          systemctl status nginx || true
