name: Backup Jenkins Jobs

on:
  schedule:
    - cron: "1 * * * *"   
  workflow_dispatch:      

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      JENKINS_JOBS_DIR: /var/lib/jenkins/jobs
      BACKUP_DIR: /var/backups/jenkins_jobs
      DATE: ${{ github.run_id }}-${{ github.run_number }}
      BACKUP_FILE: jenkins_jobs_backup_${{ github.run_id }}.tar.gz
    steps:
      - name: Create backup directory
        run: sudo mkdir -p $BACKUP_DIR

      - name: Backup Jenkins jobs
        run: |
          sudo tar -czf $BACKUP_DIR/$BACKUP_FILE -C $JENKINS_JOBS_DIR .

      - name: Cleanup old backups (older than 7 days)
        run: |
          sudo find $BACKUP_DIR -type f -name "jenkins_jobs_backup_*.tar.gz" -mtime +7 -exec rm -f {} \;

      - name: Success message
        if: success()
        run: echo "successful"

      - name: Failure message
        if: failure()
        run: echo "failed"