name: Maven Build (Manual Clone)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name:  checkout repository
        uses: actions/checkout@v3

      
      - name: Clone repository
        run: |
          git clone https://github.com/taylor-training/time-tracker.git'
          cd <time-tracker>
          ls -l

      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      
      - name: Build with Maven
        run: |
          mvn clean install